function eegOut=arrToEvent(eeg,evArr,EventName)
    T = table(evArr',ones(length(evArr),1),...
        zeros(length(evArr),1),ones(length(evArr),1),...
        [1:length(evArr)]',repmat(EventName,length(evArr),1),...
        repmat('Response',length(evArr),1),...
        [1:length(evArr)]','VariableNames',fieldnames(eeg.event)');
    eegOut=eeg;
    eegOut.event=table2struct(T);
end
